spring:
  datasource:
    url: jdbc:mysql://mysql.default:3306/tb_product?characterEncoding=utf-8&useSSL=false
    username: root
    password: zhouchongru1
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service.stockmgr.svc.cluster.local:8888/eureka