server:
  port: 8010
spring:
  application:
    name: product-service
  profiles:
    active: k8s
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tb_product?characterEncoding=utf-8&useSSL=false
    username: hit
    password: hit
    driver-class-name: com.mysql.jdbc.Driver